#pragma once
#include <Base/Types.h>
#include <Base/Container/ConcurrentQueue.h>

#include <FileFormat/Novus/Model/ComplexModel.h>

#include <robinhood/robinhood.h>
#include <enkiTS/TaskScheduler.h>

#include <limits>
#include <queue>

namespace Model
{
    struct ComplexModel;
}
class ModelRenderer;

namespace Animation
{
    using ModelID = u32;
    using InstanceID = u32;
    using SequenceID = u16;

    static constexpr u16 InvalidSequenceID = std::numeric_limits<u16>().max();

    enum class Type
    {
        Invalid = -1,
        Stand = 0,
        Death = 1,
        Spell = 2,
        Stop = 3,
        Walk = 4,
        Run = 5,
        Dead = 6,
        Rise = 7,
        StandWound = 8,
        CombatWound = 9,
        CombatCritical = 10,
        ShuffleLeft = 11,
        ShuffleRight = 12,
        Walkbackwards = 13,
        Stun = 14,
        HandsClosed = 15,
        AttackUnarmed = 16,
        Attack1H = 17,
        Attack2H = 18,
        Attack2HL = 19,
        ParryUnarmed = 20,
        Parry1H = 21,
        Parry2H = 22,
        Parry2HL = 23,
        ShieldBlock = 24,
        ReadyUnarmed = 25,
        Ready1H = 26,
        Ready2H = 27,
        Ready2HL = 28,
        ReadyBow = 29,
        Dodge = 30,
        SpellPrecast = 31,
        SpellCast = 32,
        SpellCastArea = 33,
        NPCWelcome = 34,
        NPCGoodbye = 35,
        Block = 36,
        JumpStart = 37,
        Jump = 38,
        JumpEnd = 39,
        Fall = 40,
        SwimIdle = 41,
        Swim = 42,
        SwimLeft = 43,
        SwimRight = 44,
        SwimBackwards = 45,
        AttackBow = 46,
        FireBow = 47,
        ReadyRifle = 48,
        AttackRifle = 49,
        Loot = 50,
        ReadySpellDirected = 51,
        ReadySpellOmni = 52,
        SpellCastDirected = 53,
        SpellCastOmni = 54,
        BattleRoar = 55,
        ReadyAbility = 56,
        Special1H = 57,
        Special2H = 58,
        ShieldBash = 59,
        EmoteTalk = 60,
        EmoteEat = 61,
        EmoteWork = 62,
        EmoteUseStanding = 63,
        EmoteTalkExclamation = 64,
        EmoteTalkQuestion = 65,
        EmoteBow = 66,
        EmoteWave = 67,
        EmoteCheer = 68,
        EmoteDance = 69,
        EmoteLaugh = 70,
        EmoteSleep = 71,
        EmoteSitGround = 72,
        EmoteRude = 73,
        EmoteRoar = 74,
        EmoteKneel = 75,
        EmoteKiss = 76,
        EmoteCry = 77,
        EmoteChicken = 78,
        EmoteBeg = 79,
        EmoteApplaud = 80,
        EmoteShout = 81,
        EmoteFlex = 82,
        EmoteShy = 83,
        EmotePoint = 84,
        Attack1HPierce = 85,
        Attack2HLoosePierce = 86,
        AttackOff = 87,
        AttackOffPierce = 88,
        Sheath = 89,
        HipSheath = 90,
        Mount = 91,
        RunRight = 92,
        RunLeft = 93,
        MountSpecial = 94,
        Kick = 95,
        SitGroundDown = 96,
        SitGround = 97,
        SitGroundUp = 98,
        SleepDown = 99,
        Sleep = 100,
        SleepUp = 101,
        SitChairLow = 102,
        SitChairMed = 103,
        SitChairHigh = 104,
        LoadBow = 105,
        LoadRifle = 106,
        AttackThrown = 107,
        ReadyThrown = 108,
        HoldBow = 109,
        HoldRifle = 110,
        HoldThrown = 111,
        LoadThrown = 112,
        EmoteSalute = 113,
        KneelStart = 114,
        KneelLoop = 115,
        KneelEnd = 116,
        AttackUnarmedOff = 117,
        SpecialUnarmed = 118,
        StealthWalk = 119,
        StealthStand = 120,
        Knockdown = 121,
        EatingLoop = 122,
        UseStandingLoop = 123,
        ChannelCastDirected = 124,
        ChannelCastOmni = 125,
        Whirlwind = 126,
        Birth = 127,
        UseStandingStart = 128,
        UseStandingEnd = 129,
        CreatureSpecial = 130,
        Drown = 131,
        Drowned = 132,
        FishingCast = 133,
        FishingLoop = 134,
        Fly = 135,
        EmoteWorkNoSheathe = 136,
        EmoteStunNoSheathe = 137,
        EmoteUseStandingNoSheathe = 138,
        SpellSleepDown = 139,
        SpellKneelStart = 140,
        SpellKneelLoop = 141,
        SpellKneelEnd = 142,
        Sprint = 143,
        InFlight = 144,
        Spawn = 145,
        Close = 146,
        Closed = 147,
        Open = 148,
        Opened = 149,
        Destroy = 150,
        Destroyed = 151,
        Rebuild = 152,
        Custom0 = 153,
        Custom1 = 154,
        Custom2 = 155,
        Custom3 = 156,
        Despawn = 157,
        Hold = 158,
        Decay = 159,
        BowPull = 160,
        BowRelease = 161,
        ShipStart = 162,
        ShipMoving = 163,
        ShipStop = 164,
        GroupArrow = 165,
        Arrow = 166,
        CorpseArrow = 167,
        GuideArrow = 168,
        Sway = 169,
        DruidCatPounce = 170,
        DruidCatRip = 171,
        DruidCatRake = 172,
        DruidCatRavage = 173,
        DruidCatClaw = 174,
        DruidCatCower = 175,
        DruidBearSwipe = 176,
        DruidBearBite = 177,
        DruidBearMaul = 178,
        DruidBearBash = 179,
        DragonTail = 180,
        DragonStomp = 181,
        DragonSpit = 182,
        DragonSpitHover = 183,
        DragonSpitFly = 184,
        EmoteYes = 185,
        EmoteNo = 186,
        JumpLandRun = 187,
        LootHold = 188,
        LootUp = 189,
        StandHigh = 190,
        Impact = 191,
        LiftOff = 192,
        Hover = 193,
        SuccubusEntice = 194,
        EmoteTrain = 195,
        EmoteDead = 196,
        EmoteDanceOnce = 197,
        Deflect = 198,
        EmoteEatNoSheathe = 199,
        Land = 200,
        Submerge = 201,
        Submerged = 202,
        Cannibalize = 203,
        ArrowBirth = 204,
        GroupArrowBirth = 205,
        CorpseArrowBirth = 206,
        GuideArrowBirth = 207,
        EmoteTalkNoSheathe = 208,
        EmotePointNoSheathe = 209,
        EmoteSaluteNoSheathe = 210,
        EmoteDanceSpecial = 211,
        Mutilate = 212,
        CustomSpell01 = 213,
        CustomSpell02 = 214,
        CustomSpell03 = 215,
        CustomSpell04 = 216,
        CustomSpell05 = 217,
        CustomSpell06 = 218,
        CustomSpell07 = 219,
        CustomSpell08 = 220,
        CustomSpell09 = 221,
        CustomSpell10 = 222,
        StealthRun = 223,
        Emerge = 224,
        Cower = 225,
        Grab = 226,
        GrabClosed = 227,
        GrabThrown = 228,
        FlyStand = 229,
        FlyDeath = 230,
        FlySpell = 231,
        FlyStop = 232,
        FlyWalk = 233,
        FlyRun = 234,
        FlyDead = 235,
        FlyRise = 236,
        FlyStandWound = 237,
        FlyCombatWound = 238,
        FlyCombatCritical = 239,
        FlyShuffleLeft = 240,
        FlyShuffleRight = 241,
        FlyWalkbackwards = 242,
        FlyStun = 243,
        FlyHandsClosed = 244,
        FlyAttackUnarmed = 245,
        FlyAttack1H = 246,
        FlyAttack2H = 247,
        FlyAttack2HL = 248,
        FlyParryUnarmed = 249,
        FlyParry1H = 250,
        FlyParry2H = 251,
        FlyParry2HL = 252,
        FlyShieldBlock = 253,
        FlyReadyUnarmed = 254,
        FlyReady1H = 255,
        FlyReady2H = 256,
        FlyReady2HL = 257,
        FlyReadyBow = 258,
        FlyDodge = 259,
        FlySpellPrecast = 260,
        FlySpellCast = 261,
        FlySpellCastArea = 262,
        FlyNPCWelcome = 263,
        FlyNPCGoodbye = 264,
        FlyBlock = 265,
        FlyJumpStart = 266,
        FlyJump = 267,
        FlyJumpEnd = 268,
        FlyFall = 269,
        FlySwimIdle = 270,
        FlySwim = 271,
        FlySwimLeft = 272,
        FlySwimRight = 273,
        FlySwimBackwards = 274,
        FlyAttackBow = 275,
        FlyFireBow = 276,
        FlyReadyRifle = 277,
        FlyAttackRifle = 278,
        FlyLoot = 279,
        FlyReadySpellDirected = 280,
        FlyReadySpellOmni = 281,
        FlySpellCastDirected = 282,
        FlySpellCastOmni = 283,
        FlyBattleRoar = 284,
        FlyReadyAbility = 285,
        FlySpecial1H = 286,
        FlySpecial2H = 287,
        FlyShieldBash = 288,
        FlyEmoteTalk = 289,
        FlyEmoteEat = 290,
        FlyEmoteWork = 291,
        FlyEmoteUseStanding = 292,
        FlyEmoteTalkExclamation = 293,
        FlyEmoteTalkQuestion = 294,
        FlyEmoteBow = 295,
        FlyEmoteWave = 296,
        FlyEmoteCheer = 297,
        FlyEmoteDance = 298,
        FlyEmoteLaugh = 299,
        FlyEmoteSleep = 300,
        FlyEmoteSitGround = 301,
        FlyEmoteRude = 302,
        FlyEmoteRoar = 303,
        FlyEmoteKneel = 304,
        FlyEmoteKiss = 305,
        FlyEmoteCry = 306,
        FlyEmoteChicken = 307,
        FlyEmoteBeg = 308,
        FlyEmoteApplaud = 309,
        FlyEmoteShout = 310,
        FlyEmoteFlex = 311,
        FlyEmoteShy = 312,
        FlyEmotePoint = 313,
        FlyAttack1HPierce = 314,
        FlyAttack2HLoosePierce = 315,
        FlyAttackOff = 316,
        FlyAttackOffPierce = 317,
        FlySheath = 318,
        FlyHipSheath = 319,
        FlyMount = 320,
        FlyRunRight = 321,
        FlyRunLeft = 322,
        FlyMountSpecial = 323,
        FlyKick = 324,
        FlySitGroundDown = 325,
        FlySitGround = 326,
        FlySitGroundUp = 327,
        FlySleepDown = 328,
        FlySleep = 329,
        FlySleepUp = 330,
        FlySitChairLow = 331,
        FlySitChairMed = 332,
        FlySitChairHigh = 333,
        FlyLoadBow = 334,
        FlyLoadRifle = 335,
        FlyAttackThrown = 336,
        FlyReadyThrown = 337,
        FlyHoldBow = 338,
        FlyHoldRifle = 339,
        FlyHoldThrown = 340,
        FlyLoadThrown = 341,
        FlyEmoteSalute = 342,
        FlyKneelStart = 343,
        FlyKneelLoop = 344,
        FlyKneelEnd = 345,
        FlyAttackUnarmedOff = 346,
        FlySpecialUnarmed = 347,
        FlyStealthWalk = 348,
        FlyStealthStand = 349,
        FlyKnockdown = 350,
        FlyEatingLoop = 351,
        FlyUseStandingLoop = 352,
        FlyChannelCastDirected = 353,
        FlyChannelCastOmni = 354,
        FlyWhirlwind = 355,
        FlyBirth = 356,
        FlyUseStandingStart = 357,
        FlyUseStandingEnd = 358,
        FlyCreatureSpecial = 359,
        FlyDrown = 360,
        FlyDrowned = 361,
        FlyFishingCast = 362,
        FlyFishingLoop = 363,
        FlyFly = 364,
        FlyEmoteWorkNoSheathe = 365,
        FlyEmoteStunNoSheathe = 366,
        FlyEmoteUseStandingNoSheathe = 367,
        FlySpellSleepDown = 368,
        FlySpellKneelStart = 369,
        FlySpellKneelLoop = 370,
        FlySpellKneelEnd = 371,
        FlySprint = 372,
        FlyInFlight = 373,
        FlySpawn = 374,
        FlyClose = 375,
        FlyClosed = 376,
        FlyOpen = 377,
        FlyOpened = 378,
        FlyDestroy = 379,
        FlyDestroyed = 380,
        FlyRebuild = 381,
        FlyCustom0 = 382,
        FlyCustom1 = 383,
        FlyCustom2 = 384,
        FlyCustom3 = 385,
        FlyDespawn = 386,
        FlyHold = 387,
        FlyDecay = 388,
        FlyBowPull = 389,
        FlyBowRelease = 390,
        FlyShipStart = 391,
        FlyShipMoving = 392,
        FlyShipStop = 393,
        FlyGroupArrow = 394,
        FlyArrow = 395,
        FlyCorpseArrow = 396,
        FlyGuideArrow = 397,
        FlySway = 398,
        FlyDruidCatPounce = 399,
        FlyDruidCatRip = 400,
        FlyDruidCatRake = 401,
        FlyDruidCatRavage = 402,
        FlyDruidCatClaw = 403,
        FlyDruidCatCower = 404,
        FlyDruidBearSwipe = 405,
        FlyDruidBearBite = 406,
        FlyDruidBearMaul = 407,
        FlyDruidBearBash = 408,
        FlyDragonTail = 409,
        FlyDragonStomp = 410,
        FlyDragonSpit = 411,
        FlyDragonSpitHover = 412,
        FlyDragonSpitFly = 413,
        FlyEmoteYes = 414,
        FlyEmoteNo = 415,
        FlyJumpLandRun = 416,
        FlyLootHold = 417,
        FlyLootUp = 418,
        FlyStandHigh = 419,
        FlyImpact = 420,
        FlyLiftOff = 421,
        FlyHover = 422,
        FlySuccubusEntice = 423,
        FlyEmoteTrain = 424,
        FlyEmoteDead = 425,
        FlyEmoteDanceOnce = 426,
        FlyDeflect = 427,
        FlyEmoteEatNoSheathe = 428,
        FlyLand = 429,
        FlySubmerge = 430,
        FlySubmerged = 431,
        FlyCannibalize = 432,
        FlyArrowBirth = 433,
        FlyGroupArrowBirth = 434,
        FlyCorpseArrowBirth = 435,
        FlyGuideArrowBirth = 436,
        FlyEmoteTalkNoSheathe = 437,
        FlyEmotePointNoSheathe = 438,
        FlyEmoteSaluteNoSheathe = 439,
        FlyEmoteDanceSpecial = 440,
        FlyMutilate = 441,
        FlyCustomSpell01 = 442,
        FlyCustomSpell02 = 443,
        FlyCustomSpell03 = 444,
        FlyCustomSpell04 = 445,
        FlyCustomSpell05 = 446,
        FlyCustomSpell06 = 447,
        FlyCustomSpell07 = 448,
        FlyCustomSpell08 = 449,
        FlyCustomSpell09 = 450,
        FlyCustomSpell10 = 451,
        FlyStealthRun = 452,
        FlyEmerge = 453,
        FlyCower = 454,
        FlyGrab = 455,
        FlyGrabClosed = 456,
        FlyGrabThrown = 457,
        ToFly = 458,
        ToHover = 459,
        ToGround = 460,
        FlyToFly = 461,
        FlyToHover = 462,
        FlyToGround = 463,
        Settle = 464,
        FlySettle = 465,
        DeathStart = 466,
        DeathLoop = 467,
        DeathEnd = 468,
        FlyDeathStart = 469,
        FlyDeathLoop = 470,
        FlyDeathEnd = 471,
        DeathEndHold = 472,
        FlyDeathEndHold = 473,
        Strangulate = 474,
        FlyStrangulate = 475,
        ReadyJoust = 476,
        LoadJoust = 477,
        HoldJoust = 478,
        FlyReadyJoust = 479,
        FlyLoadJoust = 480,
        FlyHoldJoust = 481,
        AttackJoust = 482,
        FlyAttackJoust = 483,
        ReclinedMount = 484,
        FlyReclinedMount = 485,
        ToAltered = 486,
        FromAltered = 487,
        FlyToAltered = 488,
        FlyFromAltered = 489,
        InStocks = 490,
        FlyInStocks = 491,
        VehicleGrab = 492,
        VehicleThrow = 493,
        FlyVehicleGrab = 494,
        FlyVehicleThrow = 495,
        ToAlteredPostSwap = 496,
        FromAlteredPostSwap = 497,
        FlyToAlteredPostSwap = 498,
        FlyFromAlteredPostSwap = 499,
        ReclinedMountPassenger = 500,
        FlyReclinedMountPassenger = 501,
        Carry2H = 502,
        Carried2H = 503,
        FlyCarry2H = 504,
        FlyCarried2H = 505,
        EmoteSniff = 506,
        EmoteFlySniff = 507,
        AttackFist1H = 508,
        FlyAttackFist1H = 509,
        AttackFist1HOff = 510,
        FlyAttackFist1HOff = 511,
        ParryFist1H = 512,
        FlyParryFist1H = 513,
        ReadyFist1H = 514,
        FlyReadyFist1H = 515,
        SpecialFist1H = 516,
        FlySpecialFist1H = 517,
        EmoteReadStart = 518,
        FlyEmoteReadStart = 519,
        EmoteReadLoop = 520,
        FlyEmoteReadLoop = 521,
        EmoteReadEnd = 522,
        FlyEmoteReadEnd = 523,
        SwimRun = 524,
        FlySwimRun = 525,
        SwimWalk = 526,
        FlySwimWalk = 527,
        SwimWalkBackwards = 528,
        FlySwimWalkBackwards = 529,
        SwimSprint = 530,
        FlySwimSprint = 531,
        MountSwimIdle = 532,
        FlyMountSwimIdle = 533,
        MountSwimBackwards = 534,
        FlyMountSwimBackwards = 535,
        MountSwimLeft = 536,
        FlyMountSwimLeft = 537,
        MountSwimRight = 538,
        FlyMountSwimRight = 539,
        MountSwimRun = 540,
        FlyMountSwimRun = 541,
        MountSwimSprint = 542,
        FlyMountSwimSprint = 543,
        MountSwimWalk = 544,
        FlyMountSwimWalk = 545,
        MountSwimWalkBackwards = 546,
        FlyMountSwimWalkBackwards = 547,
        MountFlightIdle = 548,
        FlyMountFlightIdle = 549,
        MountFlightBackwards = 550,
        FlyMountFlightBackwards = 551,
        MountFlightLeft = 552,
        FlyMountFlightLeft = 553,
        MountFlightRight = 554,
        FlyMountFlightRight = 555,
        MountFlightRun = 556,
        FlyMountFlightRun = 557,
        MountFlightSprint = 558,
        FlyMountFlightSprint = 559,
        MountFlightWalk = 560,
        FlyMountFlightWalk = 561,
        MountFlightWalkBackwards = 562,
        FlyMountFlightWalkBackwards = 563,
        MountFlightStart = 564,
        FlyMountFlightStart = 565,
        MountSwimStart = 566,
        FlyMountSwimStart = 567,
        MountSwimLand = 568,
        FlyMountSwimLand = 569,
        MountSwimLandRun = 570,
        FlyMountSwimLandRun = 571,
        MountFlightLand = 572,
        FlyMountFlightLand = 573,
        MountFlightLandRun = 574,
        FlyMountFlightLandRun = 575,
        ReadyBlowDart = 576,
        FlyReadyBlowDart = 577,
        LoadBlowDart = 578,
        FlyLoadBlowDart = 579,
        HoldBlowDart = 580,
        FlyHoldBlowDart = 581,
        AttackBlowDart = 582,
        FlyAttackBlowDart = 583,
        CarriageMount = 584,
        FlyCarriageMount = 585,
        CarriagePassengerMount = 586,
        FlyCarriagePassengerMount = 587,
        CarriageMountAttack = 588,
        FlyCarriageMountAttack = 589,
        BarTendStand = 590,
        FlyBarTendStand = 591,
        BarServerWalk = 592,
        FlyBarServerWalk = 593,
        BarServerRun = 594,
        FlyBarServerRun = 595,
        BarServerShuffleLeft = 596,
        FlyBarServerShuffleLeft = 597,
        BarServerShuffleRight = 598,
        FlyBarServerShuffleRight = 599,
        BarTendEmoteTalk = 600,
        FlyBarTendEmoteTalk = 601,
        BarTendEmotePoint = 602,
        FlyBarTendEmotePoint = 603,
        BarServerStand = 604,
        FlyBarServerStand = 605,
        BarSweepWalk = 606,
        FlyBarSweepWalk = 607,
        BarSweepRun = 608,
        FlyBarSweepRun = 609,
        BarSweepShuffleLeft = 610,
        FlyBarSweepShuffleLeft = 611,
        BarSweepShuffleRight = 612,
        FlyBarSweepShuffleRight = 613,
        BarSweepEmoteTalk = 614,
        FlyBarSweepEmoteTalk = 615,
        BarPatronSitEmotePoint = 616,
        FlyBarPatronSitEmotePoint = 617,
        MountSelfIdle = 618,
        FlyMountSelfIdle = 619,
        MountSelfWalk = 620,
        FlyMountSelfWalk = 621,
        MountSelfRun = 622,
        FlyMountSelfRun = 623,
        MountSelfSprint = 624,
        FlyMountSelfSprint = 625,
        MountSelfRunLeft = 626,
        FlyMountSelfRunLeft = 627,
        MountSelfRunRight = 628,
        FlyMountSelfRunRight = 629,
        MountSelfShuffleLeft = 630,
        FlyMountSelfShuffleLeft = 631,
        MountSelfShuffleRight = 632,
        FlyMountSelfShuffleRight = 633,
        MountSelfWalkBackwards = 634,
        FlyMountSelfWalkBackwards = 635,
        MountSelfSpecial = 636,
        FlyMountSelfSpecial = 637,
        MountSelfJump = 638,
        FlyMountSelfJump = 639,
        MountSelfJumpStart = 640,
        FlyMountSelfJumpStart = 641,
        MountSelfJumpEnd = 642,
        FlyMountSelfJumpEnd = 643,
        MountSelfJumpLandRun = 644,
        FlyMountSelfJumpLandRun = 645,
        MountSelfStart = 646,
        FlyMountSelfStart = 647,
        MountSelfFall = 648,
        FlyMountSelfFall = 649,
        Count
    };
    static const char* AnimationNames[(i32)Type::Count] =
    {
        "Stand",
        "Death",
        "Spell",
        "Stop",
        "Walk",
        "Run",
        "Dead",
        "Rise",
        "StandWound",
        "CombatWound",
        "CombatCritical",
        "ShuffleLeft",
        "ShuffleRight",
        "Walkbackwards",
        "Stun",
        "HandsClosed",
        "AttackUnarmed",
        "Attack1H",
        "Attack2H",
        "Attack2HL",
        "ParryUnarmed",
        "Parry1H",
        "Parry2H",
        "Parry2HL",
        "ShieldBlock",
        "ReadyUnarmed",
        "Ready1H",
        "Ready2H",
        "Ready2HL",
        "ReadyBow",
        "Dodge",
        "SpellPrecast",
        "SpellCast",
        "SpellCastArea",
        "NPCWelcome",
        "NPCGoodbye",
        "Block",
        "JumpStart",
        "Jump",
        "JumpEnd",
        "Fall",
        "SwimIdle",
        "Swim",
        "SwimLeft",
        "SwimRight",
        "SwimBackwards",
        "AttackBow",
        "FireBow",
        "ReadyRifle",
        "AttackRifle",
        "Loot",
        "ReadySpellDirected",
        "ReadySpellOmni",
        "SpellCastDirected",
        "SpellCastOmni",
        "BattleRoar",
        "ReadyAbility",
        "Special1H",
        "Special2H",
        "ShieldBash",
        "EmoteTalk",
        "EmoteEat",
        "EmoteWork",
        "EmoteUseStanding",
        "EmoteTalkExclamation",
        "EmoteTalkQuestion",
        "EmoteBow",
        "EmoteWave",
        "EmoteCheer",
        "EmoteDance",
        "EmoteLaugh",
        "EmoteSleep",
        "EmoteSitGround",
        "EmoteRude",
        "EmoteRoar",
        "EmoteKneel",
        "EmoteKiss",
        "EmoteCry",
        "EmoteChicken",
        "EmoteBeg",
        "EmoteApplaud",
        "EmoteShout",
        "EmoteFlex",
        "EmoteShy",
        "EmotePoint",
        "Attack1HPierce",
        "Attack2HLoosePierce",
        "AttackOff",
        "AttackOffPierce",
        "Sheath",
        "HipSheath",
        "Mount",
        "RunRight",
        "RunLeft",
        "MountSpecial",
        "Kick",
        "SitGroundDown",
        "SitGround",
        "SitGroundUp",
        "SleepDown",
        "Sleep",
        "SleepUp",
        "SitChairLow",
        "SitChairMed",
        "SitChairHigh",
        "LoadBow",
        "LoadRifle",
        "AttackThrown",
        "ReadyThrown",
        "HoldBow",
        "HoldRifle",
        "HoldThrown",
        "LoadThrown",
        "EmoteSalute",
        "KneelStart",
        "KneelLoop",
        "KneelEnd",
        "AttackUnarmedOff",
        "SpecialUnarmed",
        "StealthWalk",
        "StealthStand",
        "Knockdown",
        "EatingLoop",
        "UseStandingLoop",
        "ChannelCastDirected",
        "ChannelCastOmni",
        "Whirlwind",
        "Birth",
        "UseStandingStart",
        "UseStandingEnd",
        "CreatureSpecial",
        "Drown",
        "Drowned",
        "FishingCast",
        "FishingLoop",
        "Fly",
        "EmoteWorkNoSheathe",
        "EmoteStunNoSheathe",
        "EmoteUseStandingNoSheathe",
        "SpellSleepDown",
        "SpellKneelStart",
        "SpellKneelLoop",
        "SpellKneelEnd",
        "Sprint",
        "InFlight",
        "Spawn",
        "Close",
        "Closed",
        "Open",
        "Opened",
        "Destroy",
        "Destroyed",
        "Rebuild",
        "Custom0",
        "Custom1",
        "Custom2",
        "Custom3",
        "Despawn",
        "Hold",
        "Decay",
        "BowPull",
        "BowRelease",
        "ShipStart",
        "ShipMoving",
        "ShipStop",
        "GroupArrow",
        "Arrow",
        "CorpseArrow",
        "GuideArrow",
        "Sway",
        "DruidCatPounce",
        "DruidCatRip",
        "DruidCatRake",
        "DruidCatRavage",
        "DruidCatClaw",
        "DruidCatCower",
        "DruidBearSwipe",
        "DruidBearBite",
        "DruidBearMaul",
        "DruidBearBash",
        "DragonTail",
        "DragonStomp",
        "DragonSpit",
        "DragonSpitHover",
        "DragonSpitFly",
        "EmoteYes",
        "EmoteNo",
        "JumpLandRun",
        "LootHold",
        "LootUp",
        "StandHigh",
        "Impact",
        "LiftOff",
        "Hover",
        "SuccubusEntice",
        "EmoteTrain",
        "EmoteDead",
        "EmoteDanceOnce",
        "Deflect",
        "EmoteEatNoSheathe",
        "Land",
        "Submerge",
        "Submerged",
        "Cannibalize",
        "ArrowBirth",
        "GroupArrowBirth",
        "CorpseArrowBirth",
        "GuideArrowBirth",
        "EmoteTalkNoSheathe",
        "EmotePointNoSheathe",
        "EmoteSaluteNoSheathe",
        "EmoteDanceSpecial",
        "Mutilate",
        "CustomSpell01",
        "CustomSpell02",
        "CustomSpell03",
        "CustomSpell04",
        "CustomSpell05",
        "CustomSpell06",
        "CustomSpell07",
        "CustomSpell08",
        "CustomSpell09",
        "CustomSpell10",
        "StealthRun",
        "Emerge",
        "Cower",
        "Grab",
        "GrabClosed",
        "GrabThrown",
        "FlyStand",
        "FlyDeath",
        "FlySpell",
        "FlyStop",
        "FlyWalk",
        "FlyRun",
        "FlyDead",
        "FlyRise",
        "FlyStandWound",
        "FlyCombatWound",
        "FlyCombatCritical",
        "FlyShuffleLeft",
        "FlyShuffleRight",
        "FlyWalkbackwards",
        "FlyStun",
        "FlyHandsClosed",
        "FlyAttackUnarmed",
        "FlyAttack1H",
        "FlyAttack2H",
        "FlyAttack2HL",
        "FlyParryUnarmed",
        "FlyParry1H",
        "FlyParry2H",
        "FlyParry2HL",
        "FlyShieldBlock",
        "FlyReadyUnarmed",
        "FlyReady1H",
        "FlyReady2H",
        "FlyReady2HL",
        "FlyReadyBow",
        "FlyDodge",
        "FlySpellPrecast",
        "FlySpellCast",
        "FlySpellCastArea",
        "FlyNPCWelcome",
        "FlyNPCGoodbye",
        "FlyBlock",
        "FlyJumpStart",
        "FlyJump",
        "FlyJumpEnd",
        "FlyFall",
        "FlySwimIdle",
        "FlySwim",
        "FlySwimLeft",
        "FlySwimRight",
        "FlySwimBackwards",
        "FlyAttackBow",
        "FlyFireBow",
        "FlyReadyRifle",
        "FlyAttackRifle",
        "FlyLoot",
        "FlyReadySpellDirected",
        "FlyReadySpellOmni",
        "FlySpellCastDirected",
        "FlySpellCastOmni",
        "FlyBattleRoar",
        "FlyReadyAbility",
        "FlySpecial1H",
        "FlySpecial2H",
        "FlyShieldBash",
        "FlyEmoteTalk",
        "FlyEmoteEat",
        "FlyEmoteWork",
        "FlyEmoteUseStanding",
        "FlyEmoteTalkExclamation",
        "FlyEmoteTalkQuestion",
        "FlyEmoteBow",
        "FlyEmoteWave",
        "FlyEmoteCheer",
        "FlyEmoteDance",
        "FlyEmoteLaugh",
        "FlyEmoteSleep",
        "FlyEmoteSitGround",
        "FlyEmoteRude",
        "FlyEmoteRoar",
        "FlyEmoteKneel",
        "FlyEmoteKiss",
        "FlyEmoteCry",
        "FlyEmoteChicken",
        "FlyEmoteBeg",
        "FlyEmoteApplaud",
        "FlyEmoteShout",
        "FlyEmoteFlex",
        "FlyEmoteShy",
        "FlyEmotePoint",
        "FlyAttack1HPierce",
        "FlyAttack2HLoosePierce",
        "FlyAttackOff",
        "FlyAttackOffPierce",
        "FlySheath",
        "FlyHipSheath",
        "FlyMount",
        "FlyRunRight",
        "FlyRunLeft",
        "FlyMountSpecial",
        "FlyKick",
        "FlySitGroundDown",
        "FlySitGround",
        "FlySitGroundUp",
        "FlySleepDown",
        "FlySleep",
        "FlySleepUp",
        "FlySitChairLow",
        "FlySitChairMed",
        "FlySitChairHigh",
        "FlyLoadBow",
        "FlyLoadRifle",
        "FlyAttackThrown",
        "FlyReadyThrown",
        "FlyHoldBow",
        "FlyHoldRifle",
        "FlyHoldThrown",
        "FlyLoadThrown",
        "FlyEmoteSalute",
        "FlyKneelStart",
        "FlyKneelLoop",
        "FlyKneelEnd",
        "FlyAttackUnarmedOff",
        "FlySpecialUnarmed",
        "FlyStealthWalk",
        "FlyStealthStand",
        "FlyKnockdown",
        "FlyEatingLoop",
        "FlyUseStandingLoop",
        "FlyChannelCastDirected",
        "FlyChannelCastOmni",
        "FlyWhirlwind",
        "FlyBirth",
        "FlyUseStandingStart",
        "FlyUseStandingEnd",
        "FlyCreatureSpecial",
        "FlyDrown",
        "FlyDrowned",
        "FlyFishingCast",
        "FlyFishingLoop",
        "FlyFly",
        "FlyEmoteWorkNoSheathe",
        "FlyEmoteStunNoSheathe",
        "FlyEmoteUseStandingNoSheathe",
        "FlySpellSleepDown",
        "FlySpellKneelStart",
        "FlySpellKneelLoop",
        "FlySpellKneelEnd",
        "FlySprint",
        "FlyInFlight",
        "FlySpawn",
        "FlyClose",
        "FlyClosed",
        "FlyOpen",
        "FlyOpened",
        "FlyDestroy",
        "FlyDestroyed",
        "FlyRebuild",
        "FlyCustom0",
        "FlyCustom1",
        "FlyCustom2",
        "FlyCustom3",
        "FlyDespawn",
        "FlyHold",
        "FlyDecay",
        "FlyBowPull",
        "FlyBowRelease",
        "FlyShipStart",
        "FlyShipMoving",
        "FlyShipStop",
        "FlyGroupArrow",
        "FlyArrow",
        "FlyCorpseArrow",
        "FlyGuideArrow",
        "FlySway",
        "FlyDruidCatPounce",
        "FlyDruidCatRip",
        "FlyDruidCatRake",
        "FlyDruidCatRavage",
        "FlyDruidCatClaw",
        "FlyDruidCatCower",
        "FlyDruidBearSwipe",
        "FlyDruidBearBite",
        "FlyDruidBearMaul",
        "FlyDruidBearBash",
        "FlyDragonTail",
        "FlyDragonStomp",
        "FlyDragonSpit",
        "FlyDragonSpitHover",
        "FlyDragonSpitFly",
        "FlyEmoteYes",
        "FlyEmoteNo",
        "FlyJumpLandRun",
        "FlyLootHold",
        "FlyLootUp",
        "FlyStandHigh",
        "FlyImpact",
        "FlyLiftOff",
        "FlyHover",
        "FlySuccubusEntice",
        "FlyEmoteTrain",
        "FlyEmoteDead",
        "FlyEmoteDanceOnce",
        "FlyDeflect",
        "FlyEmoteEatNoSheathe",
        "FlyLand",
        "FlySubmerge",
        "FlySubmerged",
        "FlyCannibalize",
        "FlyArrowBirth",
        "FlyGroupArrowBirth",
        "FlyCorpseArrowBirth",
        "FlyGuideArrowBirth",
        "FlyEmoteTalkNoSheathe",
        "FlyEmotePointNoSheathe",
        "FlyEmoteSaluteNoSheathe",
        "FlyEmoteDanceSpecial",
        "FlyMutilate",
        "FlyCustomSpell01",
        "FlyCustomSpell02",
        "FlyCustomSpell03",
        "FlyCustomSpell04",
        "FlyCustomSpell05",
        "FlyCustomSpell06",
        "FlyCustomSpell07",
        "FlyCustomSpell08",
        "FlyCustomSpell09",
        "FlyCustomSpell10",
        "FlyStealthRun",
        "FlyEmerge",
        "FlyCower",
        "FlyGrab",
        "FlyGrabClosed",
        "FlyGrabThrown",
        "ToFly",
        "ToHover",
        "ToGround",
        "FlyToFly",
        "FlyToHover",
        "FlyToGround",
        "Settle",
        "FlySettle",
        "DeathStart",
        "DeathLoop",
        "DeathEnd",
        "FlyDeathStart",
        "FlyDeathLoop",
        "FlyDeathEnd",
        "DeathEndHold",
        "FlyDeathEndHold",
        "Strangulate",
        "FlyStrangulate",
        "ReadyJoust",
        "LoadJoust",
        "HoldJoust",
        "FlyReadyJoust",
        "FlyLoadJoust",
        "FlyHoldJoust",
        "AttackJoust",
        "FlyAttackJoust",
        "ReclinedMount",
        "FlyReclinedMount",
        "ToAltered",
        "FromAltered",
        "FlyToAltered",
        "FlyFromAltered",
        "InStocks",
        "FlyInStocks",
        "VehicleGrab",
        "VehicleThrow",
        "FlyVehicleGrab",
        "FlyVehicleThrow",
        "ToAlteredPostSwap",
        "FromAlteredPostSwap",
        "FlyToAlteredPostSwap",
        "FlyFromAlteredPostSwap",
        "ReclinedMountPassenger",
        "FlyReclinedMountPassenger",
        "Carry2H",
        "Carried2H",
        "FlyCarry2H",
        "FlyCarried2H",
        "EmoteSniff",
        "EmoteFlySniff",
        "AttackFist1H",
        "FlyAttackFist1H",
        "AttackFist1HOff",
        "FlyAttackFist1HOff",
        "ParryFist1H",
        "FlyParryFist1H",
        "ReadyFist1H",
        "FlyReadyFist1H",
        "SpecialFist1H",
        "FlySpecialFist1H",
        "EmoteReadStart",
        "FlyEmoteReadStart",
        "EmoteReadLoop",
        "FlyEmoteReadLoop",
        "EmoteReadEnd",
        "FlyEmoteReadEnd",
        "SwimRun",
        "FlySwimRun",
        "SwimWalk",
        "FlySwimWalk",
        "SwimWalkBackwards",
        "FlySwimWalkBackwards",
        "SwimSprint",
        "FlySwimSprint",
        "MountSwimIdle",
        "FlyMountSwimIdle",
        "MountSwimBackwards",
        "FlyMountSwimBackwards",
        "MountSwimLeft",
        "FlyMountSwimLeft",
        "MountSwimRight",
        "FlyMountSwimRight",
        "MountSwimRun",
        "FlyMountSwimRun",
        "MountSwimSprint",
        "FlyMountSwimSprint",
        "MountSwimWalk",
        "FlyMountSwimWalk",
        "MountSwimWalkBackwards",
        "FlyMountSwimWalkBackwards",
        "MountFlightIdle",
        "FlyMountFlightIdle",
        "MountFlightBackwards",
        "FlyMountFlightBackwards",
        "MountFlightLeft",
        "FlyMountFlightLeft",
        "MountFlightRight",
        "FlyMountFlightRight",
        "MountFlightRun",
        "FlyMountFlightRun",
        "MountFlightSprint",
        "FlyMountFlightSprint",
        "MountFlightWalk",
        "FlyMountFlightWalk",
        "MountFlightWalkBackwards",
        "FlyMountFlightWalkBackwards",
        "MountFlightStart",
        "FlyMountFlightStart",
        "MountSwimStart",
        "FlyMountSwimStart",
        "MountSwimLand",
        "FlyMountSwimLand",
        "MountSwimLandRun",
        "FlyMountSwimLandRun",
        "MountFlightLand",
        "FlyMountFlightLand",
        "MountFlightLandRun",
        "FlyMountFlightLandRun",
        "ReadyBlowDart",
        "FlyReadyBlowDart",
        "LoadBlowDart",
        "FlyLoadBlowDart",
        "HoldBlowDart",
        "FlyHoldBlowDart",
        "AttackBlowDart",
        "FlyAttackBlowDart",
        "CarriageMount",
        "FlyCarriageMount",
        "CarriagePassengerMount",
        "FlyCarriagePassengerMount",
        "CarriageMountAttack",
        "FlyCarriageMountAttack",
        "BarTendStand",
        "FlyBarTendStand",
        "BarServerWalk",
        "FlyBarServerWalk",
        "BarServerRun",
        "FlyBarServerRun",
        "BarServerShuffleLeft",
        "FlyBarServerShuffleLeft",
        "BarServerShuffleRight",
        "FlyBarServerShuffleRight",
        "BarTendEmoteTalk",
        "FlyBarTendEmoteTalk",
        "BarTendEmotePoint",
        "FlyBarTendEmotePoint",
        "BarServerStand",
        "FlyBarServerStand",
        "BarSweepWalk",
        "FlyBarSweepWalk",
        "BarSweepRun",
        "FlyBarSweepRun",
        "BarSweepShuffleLeft",
        "FlyBarSweepShuffleLeft",
        "BarSweepShuffleRight",
        "FlyBarSweepShuffleRight",
        "BarSweepEmoteTalk",
        "FlyBarSweepEmoteTalk",
        "BarPatronSitEmotePoint",
        "FlyBarPatronSitEmotePoint",
        "MountSelfIdle",
        "FlyMountSelfIdle",
        "MountSelfWalk",
        "FlyMountSelfWalk",
        "MountSelfRun",
        "FlyMountSelfRun",
        "MountSelfSprint",
        "FlyMountSelfSprint",
        "MountSelfRunLeft",
        "FlyMountSelfRunLeft",
        "MountSelfRunRight",
        "FlyMountSelfRunRight",
        "MountSelfShuffleLeft",
        "FlyMountSelfShuffleLeft",
        "MountSelfShuffleRight",
        "FlyMountSelfShuffleRight",
        "MountSelfWalkBackwards",
        "FlyMountSelfWalkBackwards",
        "MountSelfSpecial",
        "FlyMountSelfSpecial",
        "MountSelfJump",
        "FlyMountSelfJump",
        "MountSelfJumpStart",
        "FlyMountSelfJumpStart",
        "MountSelfJumpEnd",
        "FlyMountSelfJumpEnd",
        "MountSelfJumpLandRun",
        "FlyMountSelfJumpLandRun",
        "MountSelfStart",
        "FlyMountSelfStart",
        "MountSelfFall",
        "FlyMountSelfFall"
    };

    enum class Bone : i16
    {
        Default = -1,
        ArmL = 0,
        ArmR = 1,
        ShoulderL = 2,
        ShoulderR = 3,
        SpineLow = 4,
        Waist = 5,
        Head = 6,
        Jaw = 7,
        IndexFingerR = 8,
        MiddleFingerR = 9,
        PinkyFingerR = 10,
        RingFingerR = 11,
        ThumbR = 12,
        IndexFingerL = 13,
        MiddleFingerL = 14,
        PinkyFingerL = 15,
        RingFingerL = 16,
        ThumbL = 17,
        $BTH = 18,
        $CSR = 19,
        $CSL = 20,
        _Breath = 21,
        _Name = 22,
        _NameMount = 23,
        $CHD = 24,
        $CCH = 25,
        Root = 26,
        Wheel1 = 27,
        Wheel2 = 28,
        Wheel3 = 29,
        Wheel4 = 30,
        Wheel5 = 31,
        Wheel6 = 32,
        Wheel7 = 33,
        Wheel8 = 34,
        FaceAttenuation = 35,
        EXP_C1_Cape1 = 36,
        EXP_C1_Cape2 = 37,
        EXP_C1_Cape3 = 38,
        EXP_C1_Cape4 = 39,
        EXP_C1_Cape5 = 40,
        EXP_C1_Tail1 = 41,
        EXP_C1_Tail2 = 42,
        EXP_C1_LoinBk1 = 43,
        EXP_C1_LoinBk2 = 44,
        EXP_C1_LoinBk3 = 45,
        EXP_C1_Spine2 = 48,
        EXP_C1_Neck1 = 49,
        EXP_C1_Neck2 = 50,
        EXP_C1_Pelvis1 = 51,
        Buckle = 52,
        Chest = 53,
        Main = 54,
        EXP_R1_Leg1Twist1 = 55,
        EXP_L1_Leg1Twist1 = 56,
        EXP_R1_Leg2Twist1 = 57,
        EXP_L1_Leg2Twist1 = 58,
        FootL = 59,
        FootR = 60,
        ElbowR = 61,
        ElbowL = 62,
        EXP_L1_Shield1 = 63,
        HandR = 64,
        HandL = 65,
        WeaponR = 66,
        WeaponL = 67,
        SpellHandL = 68,
        SpellHandR = 69,
        EXP_R1_Leg1Twist3 = 70,
        EXP_L1_Leg1Twist3 = 71,
        EXP_R1_Arm1Twist2 = 72,
        EXP_L1_Arm1Twist2 = 73,
        EXP_R1_Arm1Twist3 = 74,
        EXP_L1_Arm1Twist3 = 75,
        EXP_R1_Arm2Twist2 = 76,
        EXP_L1_Arm2Twist2 = 77,
        EXP_R1_Arm2Twist3 = 78,
        EXP_L1_Arm2Twist3 = 79,
        ForearmR = 80,
        ForearmL = 81,
        EXP_R1_Arm1Twist1 = 82,
        EXP_L1_Arm1Twist1 = 83,
        EXP_R1_Arm2Twist1 = 84,
        EXP_L1_Arm2Twist1 = 85,
        EXP_R1_FingerClawA1 = 86,
        EXP_R1_FingerClawB1 = 87,
        EXP_L1_FingerClawA1 = 88,
        EXP_L1_FingerClawB1 = 89,
        _BackCloak = 190,
        face_hair_00_M_JNT = 191,
        face_beard_00_M_JNT = 192,
        Count
    };
    static const char* BoneNames[(i16)Bone::Count] = { };

    enum class BlendOverride
    {
        Auto,
        None,
        Start,
        End,
        Both
    };

    enum class Flag
    {
        None = 0,
        Loop = 0x1,
        Freeze = 0x2,
        Frozen = 0x4, // Internal Flag
    };
    DECLARE_GENERIC_BITWISE_OPERATORS(Flag);

    inline bool HasAnimationFlag(Flag flags, Flag flag)
    {
        return (flags & flag) == flag;
    }
    inline void SetAnimationFlag(Flag& flags, Flag flag)
    {
        flags |= flag;
    }

    typedef void(*AnimationCallback)(InstanceID instanceID, Type animation, Type interruptedBy);
    struct AnimationSkeletonBone
    {
    public:
        Model::ComplexModel::Bone info;
    };
    struct AnimationSkeletonTextureTransform
    {
    public:
        Model::ComplexModel::TextureTransform info;
    };
    struct AnimationSkeleton
    {
    public:
        static constexpr ModelID InvalidID = std::numeric_limits<ModelID>().max();

        u32 modelID = InvalidID;

        std::vector<u32> globalLoops;
        std::vector<Model::ComplexModel::AnimationSequence> sequences;
        std::vector<AnimationSkeletonBone> bones;
        std::vector<AnimationSkeletonTextureTransform> textureTransforms;

        robin_hood::unordered_map<Type, u16> animationIDToFirstSequenceID;
        robin_hood::unordered_map<u16, i16> keyBoneIDToBoneID;
    };

    enum class AnimationPlayState : u32
    {
        STOPPED,
        ONESHOT,
        LOOPING
    };

    struct AnimationSequenceState
    {
    public:
        Type animation = Type::Invalid;
        SequenceID sequenceID = InvalidSequenceID;
        AnimationCallback finishedCallback = nullptr;

        Flag flags = Flag::None;
        f32 blendTimeStart = 0.0f;
        f32 blendTimeEnd = 0.0f;
        f32 progress = 0.0f;
    };

    struct AnimationBoneInstance
    {
        AnimationBoneInstance* parent = nullptr;
        quat rotationOffset = quat(1.0f, 0.0f, 0.0f, 0.0f);

        AnimationSequenceState currentAnimation = {};
        AnimationSequenceState nextAnimation = {};

        f32 timeToTransition = 0.0f;
        f32 transitionDuration = 0.0f;
    };

    struct AnimationGlobalLoopInstance
    {
    public:
        f32 currentTime = 0;
        f32 duration = 0;
    };
    struct AnimationInstance
    {
    public:
        static constexpr InstanceID InvalidID = std::numeric_limits<InstanceID>().max();

        ModelID modelID = AnimationSkeleton::InvalidID;
        InstanceID instanceID = InvalidID;

        u32 boneMatrixOffset = InvalidID;
        u32 textureTransformMatrixOffset = InvalidID;

        std::vector<AnimationGlobalLoopInstance> globalLoops;
        std::vector<AnimationBoneInstance> bones;
    };

    struct AnimationStorage
    {
    public:
        robin_hood::unordered_map<ModelID, AnimationSkeleton> skeletons;

        std::atomic<u32> instancesIndex;
        std::vector<InstanceID> instanceIDs;
        robin_hood::unordered_map<InstanceID, AnimationInstance> instanceIDToData;

        std::mutex dirtyInstancesMutex;
        std::queue<InstanceID> dirtyInstancesQueue;
        robin_hood::unordered_set<InstanceID> dirtyInstances;

        std::atomic<u32> boneMatrixIndex;
        std::vector<mat4x4> boneMatrices;

        std::atomic<u32> textureTransformMatrixIndex;
        std::vector<mat4x4> textureTransformMatrices;
    };

    class AnimationSystem
    {
    public:
        AnimationSystem(ModelRenderer* modelRenderer);

        bool HasSkeleton(ModelID modelID) { return _storage.skeletons.contains(modelID); }
        bool AddSkeleton(ModelID modelID, Model::ComplexModel& model);

        bool HasInstance(InstanceID instanceID) { return _storage.instanceIDToData.contains(instanceID); }
        bool AddInstance(ModelID modelID, InstanceID instanceID);

        bool GetCurrentAnimation(InstanceID instanceID, Bone bone, Type* primary, Type* sequence = nullptr);
        bool IsPlaying(InstanceID instanceID, Bone bone, Type animationID);
        u32 GetSequenceIDForAnimationID(ModelID modelID, Type animationID);

        i16 GetBoneIndexFromKeyBoneID(ModelID modelID, Bone bone);
        const AnimationSequenceState* GetSequenceStateForBone(const AnimationBoneInstance& boneInstance);
        const AnimationSequenceState* GetDeferredSequenceStateForBone(const AnimationBoneInstance& boneInstance, f32& timeToTransition, f32& transitionDuration);

        bool SetBoneSequence(InstanceID instanceID, Bone bone, Type animationID, Flag flags = Flag::None, BlendOverride blendOverride = BlendOverride::Auto, AnimationCallback onFinishedCallback = nullptr);
        bool SetBoneRotation(InstanceID instanceID, Bone bone, quat& rotation);

        void Update(f32 deltaTime);

        void Reserve(u32 numSkeletons, u32 numInstances, u32 numBones, u32 numTextureTransforms);
        void FitToBuffersAfterLoad();
        void Clear();

    private:
        mat4x4 GetBoneMatrix(const AnimationSkeleton& skeleton, const AnimationInstance& instance, const AnimationSkeletonBone& bone, const AnimationBoneInstance& boneInstance);
        void HandleBoneAnimation(const AnimationSkeleton& skeleton, const AnimationInstance& instance, const AnimationSkeletonBone& bone, AnimationBoneInstance& boneInstance, f32 deltaTime);
        mat4x4 GetTextureTransformMatrix(const AnimationSkeleton& skeleton, const AnimationInstance& instance, const AnimationBoneInstance& boneInstance, const AnimationSkeletonTextureTransform& textureTransform);
        
        bool HasModelRenderer() { return _modelRenderer != nullptr; }

    private:
        AnimationStorage _storage;
        ModelRenderer* _modelRenderer = nullptr;
    };
}