#pragma once
#include <Base/Types.h>

#include <entt/fwd.hpp>

#include <limits>

namespace Attachment::Defines
{
    static constexpr u16 InvalidAttachmentIndex = std::numeric_limits<u16>().max();

    enum class Type : i16
    {
        Invalid = -1,
        Shield = 0,
        HandRight = 1,
        HandLeft = 2,
        ElbowRight = 3,
        ElbowLeft = 4,
        ShoulderRight = 5,
        ShoulderLeft = 6,
        KneeRight = 7,
        KneeLet = 8,
        HipRight = 9,
        HipLeft = 10,
        Helm = 11,
        Back = 12,
        ShoulderFlapRight = 13,
        ShoulderFlapLeft = 14,
        ChestBloodFront = 15,
        ChestBloodBack = 16,
        Breath = 17,
        PlayerName = 18,
        Base = 19,
        Head = 20,
        SpellLeftHand = 21,
        SpellRightHand = 22,
        Special1 = 23,
        Special2 = 24,
        Special3 = 25,
        SheathMainHand = 26,
        SheathOffHand = 27,
        SheathShield = 28,
        PlayerNameMounted = 29,
        LargeWeaponLeft = 30,
        LargeWeaponRight = 31,
        HipWeaponLeft = 32,
        HipWeaponRight = 33,
        Chest = 34,
        HandArrow = 35,
        Bullet = 36,
        SpellHandOmni = 37,
        SpellHandDirected = 38,
        VehicleSeat1 = 39,
        VehicleSeat2 = 40,
        VehicleSeat3 = 41,
        VehicleSeat4 = 42,
        VehicleSeat5 = 43,
        VehicleSeat6 = 44,
        VehicleSeat7 = 45,
        VehicleSeat8 = 46,
        LeftFoot = 47,
        RightFoot = 48,
        ShieldNoGlove = 49,
        SpineLow = 50,
        AlteredShoulderR = 51,
        AlteredShoulderL = 52,
        BeltBuckle = 53,
        SheathCrossbow = 54,
        HeadTop = 55,
        VirtualSpellDirected = 56,
        Backpack = 57,
        Count
    };
    static const char* TypeNames[(i8)Type::Count] =
    {
        "Shield",
        "HandRight",
        "HandLeft",
        "ElbowRight",
        "ElbowLeft",
        "ShoulderRight",
        "ShoulderLeft",
        "KneeRight",
        "KneeLet",
        "HipRight",
        "HipLeft",
        "Helm",
        "Back",
        "ShoulderFlapRight",
        "ShoulderFlapLeft",
        "ChestBloodFront",
        "ChestBloodBack",
        "Breath",
        "PlayerName",
        "Base",
        "Head",
        "SpellLeftHand",
        "SpellRightHand",
        "Special1",
        "Special2",
        "Special3",
        "SheathMainHand",
        "SheathOffHand",
        "SheathShield",
        "PlayerNameMounted",
        "LargeWeaponLeft",
        "LargeWeaponRight",
        "HipWeaponLeft",
        "HipWeaponRight",
        "Chest",
        "HandArrow",
        "Bullet",
        "SpellHandOmni",
        "SpellHandDirected",
        "VehicleSeat1",
        "VehicleSeat2",
        "VehicleSeat3",
        "VehicleSeat4",
        "VehicleSeat5",
        "VehicleSeat6",
        "VehicleSeat7",
        "VehicleSeat8",
        "LeftFoot",
        "RightFoot",
        "ShieldNoGlove",
        "SpineLow",
        "AlteredShoulderR",
        "AlteredShoulderL",
        "BeltBuckle",
        "SheathCrossbow",
        "HeadTop",
        "VirtualSpellDirected",
        "Backpack"
    };
}