local UITemplates = require("@src/API/UI/Templates")
UITemplates.RegisterTemplates();

local _ = require("@src/API/UI/WidgetExtensions")
local _ = require("@src/API/UI/CursorInfo")
local _ = require("@src/API/UI/ItemSlot")
local _ = require("@src/API/UI/ActionBar")
local _ = require("@src/API/UI/MicroMenu")
local _ = require("@src/API/Game/ItemUtil")
local _ = require("@src/API/Game/GameTooltip")
local _ = require("@src/API/Game/Bag")
local _ = require("@src/API/Game/PlayerContainers")
