name: win-build

on:
  push:
  workflow_dispatch:

jobs:
  win-build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        repository: novusengine/Game

    - name: Premake
      run: |
        premake5 vs2022

    - name: Build
      run: |
        msbuild /m /p:Configuration=Debug Build/Game.sln
